pipeline {
  agent {
    docker {
      image 'node:16-alpine'
      args '-v $PWD:/main -w /main/multi-stage-multi-agent -p 3000:3000'
    }
  }
  stages {
    stage('Install') {
      steps {
        sh 'ls -la' // confirms files are present
        sh 'npm install --unsafe-perm=true'
      }
    }
    stage('Start Server') {
      steps {
        sh 'npm start'
      }
    }
    stage('Debug') {
  steps {
    sh 'find /main -name package.json'
  }
}
  }
}
