pipeline {
  agent {
    docker {
      image 'node:16-alpine'
      args '-v $PWD:/app -w /app -p 3000:3000'
    }
  }
  stages {
    stage('Install') {
      steps {
        sh 'ls -la' // confirms files are present
        sh 'npm install --unsafe-perm=true'
      }
    }
    stage('Start Server') {
      steps {
        sh 'npm start'
      }
    }
  }
}
